-- RL_Inca_CityandCivNames
-- Author: Rohan
-- DateCreated: 11/22/2017 8:48:23 PM
--------------------------------------------------------------

INSERT INTO CityNames	
		(CivilizationType,			CityName)	
VALUES	('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_2'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_3'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_4'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_5'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_6'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_7'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_8'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_9'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_10'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_11'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_12'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_13'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_14'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_15'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_16'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_17'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_18'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_19'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_20'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_21'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_22'),	
		('CIVILIZATION_RL_INCA',	'LOC_CITY_NAME_RL_INCA_23');		

INSERT INTO CivilizationCitizenNames	
		(CivilizationType,			CitizenName,								Female,		Modern)
VALUES	('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MALE_1',				0,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MALE_2',				0,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MALE_3',				0,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MALE_4',				0,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MALE_5',				0,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_FEMALE_1',				1,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_FEMALE_2',				1,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_FEMALE_3',				1,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_FEMALE_4',				1,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_FEMALE_5',				1,			0),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_MALE_1',		0,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_MALE_2',		0,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_MALE_3',		0,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_MALE_4',		0,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_MALE_5',		0,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_FEMALE_1',		1,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_FEMALE_2',		1,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_FEMALE_3',		1,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_FEMALE_4',		1,			1),
		('CIVILIZATION_RL_INCA',	'LOC_CITIZEN_RL_INCA_MODERN_FEMALE_5',		1,			1);	